version: '3.9'

services:

  sphere-animation:
    image: tensorflow/sphere:latest
    container_name: sphere-animation
    build:
      dockerfile: ./Dockerfile
    networks:
      - sphere-network
    volumes:
      - ./app:/app
    ports:
      - 15050:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: nvidia-smi
      interval: 5s
      timeout: 5s
      retries: 3
    # command: ["python3", "-m", "sphere"]
    command: sleep infinity

networks:
  sphere-network:
    name: sphere-network
    driver: bridge
    external: false
